# This file provides instructions for packaging.

`Throwable-Factory`
	perl_version_from m`Throwable::Factory`;
	version_from      m`Throwable::Factory`;
	readme_from       m`Throwable::Factory`;
	requires p`Moo 1.000006`;
	requires p`MooX::Struct 0.008`;
	requires p`Throwable::Error 0.200000`;
	requires p`namespace::sweep 0.006`;
	test_requires p`Test::More 0.88`;
	test_requires p`Try::Tiny 0`;
.

